server:
  port: 8082

#jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bee?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: rootrootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      #更新或创建数据库表结构
      ddl-auto: update
    #输出执行sql
    show-sql: true
